name: Build Rust project
on: [push]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macOS-latest]
        rust: [stable]

    steps:
    - uses: actions/checkout@v2

    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ matrix.rust }}

    - uses: Swatinem/rust-cache@v1

    - name: Run build
      run: cargo build --release

    - name: Run tests
      run: cargo test --verbose

    - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: master-${{ steps.vars.outputs.sha_short }}
        files: |
          target/release/logitech-server
          target/release/logitech-server.exe
