name: Build Rust project
on: [push]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macOS-latest]
        rust: [stable]

    steps:
    - uses: actions/checkout@v2

    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ matrix.rust }}

    - uses: Swatinem/rust-cache@v1

    - name: Run build
      run: cargo build --release
    - name: Run tests
      run: cargo test --verbose
